version: '3'

services:
  jenkins:
    container_name: jenkins
    image: makejava/jenkins:docker
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - home_data:/var/jenkins_home
    network_mode: bridge
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=tcp://192.168.0.1:2375


volumes:
  home_data: